#!/usr/bin/env bash
# Compiles every stylesheet into one SaxonJS SEF bundle: src/assets/js/fe-sef.js
#
#   FATTURA                      AssoSoftware, for the invoice itself
#   RC NS MC MT NE EC SE DT AT   the official SdI stylesheets, one per message type
#
# Run once, and again whenever a stylesheet is replaced with a newer release.
# Requires Node.js. Nothing here runs inside Business Central - it is a build-time step.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(dirname "$HERE")"
WORK="$HERE/.build"
OUT="$ROOT/src/assets/js/fe-sef.js"

INVOICE_XSL="${1:-$HERE/FoglioStileAssoSoftware.xsl}"
SDI_XSL_DIR="${2:-$HERE/sdi-xsl}"

rm -rf "$WORK"; mkdir -p "$WORK"

# ---------------------------------------------------------------- invoice sheet
#
# Two fixes, both required because SaxonJS is strict where libxslt and the browsers' native
# XSLTProcessor are lenient. Neither changes the rendered output.
#
#   1. <xsl:call-template select="."> is invalid XSLT - @select is not allowed there. Saxon
#      refuses to compile it (XTSE0090). Dropping it is a no-op: call-template never changes
#      the context node anyway.
#
#   2. format-number(NodeRef, ...) - under XSLT 3.0 the node atomises to xs:untypedAtomic and
#      the implicit cast to xs:double yields NaN, so every amount renders blank. Wrapping the
#      first argument in number() restores XSLT 1.0 behaviour. This one fails SILENTLY.
echo "==> Patching and compiling the invoice stylesheet"
perl -0pe '
    s/(<xsl:call-template\b[^>]*?)\s+select="\."/$1/g;
    s/format-number\(\s*([^,()]+?)\s*,/format-number(number($1),/g;
' "$INVOICE_XSL" > "$WORK/FATTURA.xsl"
npx --yes xslt3 -xsl:"$WORK/FATTURA.xsl" -export:"$WORK/FATTURA.sef.json" -nogo

# ---------------------------------------------------------------- SdI message sheets
#
# Two more fixes, specific to the official SdI stylesheets:
#
#   3. They declare <xsl:output version="4.0">. SaxonJS serialises HTML 5 only and raises
#      SESU0013 on anything else.
#
#   4. They match the root as a:RicevutaConsegna, bound to the fatturapa.gov.it namespace.
#      Two message schemas are in circulation - MessaggiTypes_v1.1.xsd on that namespace, and
#      SDIRicevute.xsd on ivaservizi.agenziaentrate.gov.it - and the receipts a company
#      actually receives may be either. Rewriting that ONE selector to match on local-name(),
#      with the alternate spelling where the two families differ, makes each sheet work for
#      both. It is the only expression in these stylesheets that carries a prefix; everything
#      else already selects unqualified children.
echo "==> Patching and compiling the SdI message stylesheets"
for xsl in "$SDI_XSL_DIR"/*.xsl; do
    code="$(basename "$xsl" | cut -d_ -f1)"
    perl -0pe '
        s/(<xsl:output\b[^>]*?)\bversion="4\.0"/$1version="5.0"/g;
        s{(match|select)="a:NotificaScarto"}{$1="*[local-name()=\x27NotificaScarto\x27 or local-name()=\x27RicevutaScarto\x27]"}g;
        s{(match|select)="a:NotificaMancataConsegna"}{$1="*[local-name()=\x27NotificaMancataConsegna\x27 or local-name()=\x27RicevutaImpossibilitaRecapito\x27]"}g;
        s{(match|select)="a:MetadatiInvioFile"}{$1="*[local-name()=\x27MetadatiInvioFile\x27 or local-name()=\x27FileMetadati\x27]"}g;
        s{(match|select)="a:([A-Za-z]+)"}{$1="*[local-name()=\x27$2\x27]"}g;
    ' "$xsl" > "$WORK/$code.xsl"
    npx --yes xslt3 -xsl:"$WORK/$code.xsl" -export:"$WORK/$code.sef.json" -nogo
    echo "    $code"
done

# ---------------------------------------------------------------- bundle
echo "==> Bundling into $OUT"
node -e '
const fs = require("fs"), path = require("path");
const work = process.argv[1], out = process.argv[2];
const bundle = {};
for (const f of fs.readdirSync(work).filter(f => f.endsWith(".sef.json")).sort()) {
    bundle[path.basename(f, ".sef.json")] = JSON.parse(fs.readFileSync(path.join(work, f), "utf8"));
}
const header =
  "// Auto-generated by tools/build-sef.sh - do not edit by hand.\n" +
  "//\n" +
  "// One compiled stylesheet per document kind:\n" +
  "//   FATTURA  foglio di stile AssoSoftware, per la fattura\n" +
  "//   RC NS MC NE MT EC SE DT AT   fogli ufficiali SdI, uno per tipo di ricevuta\n" +
  "//\n" +
  "// The viewer picks the entry by key; anything missing falls back to indented XML source.\n" +
  "window.FE_SEF = ";
fs.writeFileSync(out, header + JSON.stringify(bundle) + ";\n");
console.log("    " + Object.keys(bundle).join(", "));
' "$WORK" "$OUT"

rm -rf "$WORK"
echo "==> Done: $(wc -c < "$OUT") bytes"
echo
echo "The SaxonJS runtime is already in the repository:"
echo "  $ROOT/src/assets/js/saxon-js2/SaxonJS2.rt.js"
echo "Replace it only to upgrade - see https://www.saxonica.com/download/javascript.xml"
